-- ============================================================================
-- 01 - Create Column Master Keys (CMK)
-- ============================================================================
-- PREREQUISITES:
--   1. Deploy infra/main.bicep first to create Key Vault and RSA 4096-bit keys.
--   2. Note the key URIs from the deployment outputs (cmkNoEnclaveKeyUri, cmkWithEnclaveKeyUri).
--   3. Run this script in SSMS connected to AlwaysEncryptPocDb.
--
-- IMPORTANT: The KEY_PATH values below must match the AKV key URIs from Bicep output.
-- Replace the <PLACEHOLDER> values with actual URIs.
--
-- For CMK_WithEnclave, the ENCLAVE_COMPUTATIONS signature must be generated by
-- SSMS (right-click Always Encrypted Keys > New Column Master Key) or via PowerShell:
--   New-SqlColumnMasterKey -Name CMK_WithEnclave -KeyStoreProviderName AZURE_KEY_VAULT `
--     -KeyPath "<AKV-KEY-URI>" -AllowEnclaveComputations
-- ============================================================================

-- ---------------------------------------------------------------------------
-- CMK_NoEnclave — Standard Column Master Key (no enclave computations)
-- Used by: EncryptedNoEnclave table, CEK_NoEnclave
-- ---------------------------------------------------------------------------
CREATE COLUMN MASTER KEY [CMK_NoEnclave]
WITH (
    KEY_STORE_PROVIDER_NAME = N'AZURE_KEY_VAULT',
    KEY_PATH = N'<CMK_NO_ENCLAVE_AKV_KEY_URI>'
    -- Example: KEY_PATH = N'https://kv-ae-poc-xxxxx.vault.azure.net/keys/CMK-NoEnclave/abc123...'
);
GO

-- ---------------------------------------------------------------------------
-- CMK_WithEnclave — Enclave-enabled Column Master Key
-- Used by: EncryptedWithEnclave table, CEK_WithEnclave
-- The ENCLAVE_COMPUTATIONS clause enables this CMK for VBS enclave operations.
-- The SIGNATURE value must be generated by SSMS or PowerShell during provisioning.
-- ---------------------------------------------------------------------------
CREATE COLUMN MASTER KEY [CMK_WithEnclave]
WITH (
    KEY_STORE_PROVIDER_NAME = N'AZURE_KEY_VAULT',
    KEY_PATH = N'<CMK_WITH_ENCLAVE_AKV_KEY_URI>',
    -- Example: KEY_PATH = N'https://kv-ae-poc-xxxxx.vault.azure.net/keys/CMK-WithEnclave/def456...'
    ENCLAVE_COMPUTATIONS (
        SIGNATURE = <ENCLAVE_SIGNATURE_HEX>
        -- Generated by SSMS or PowerShell. This is a hex value like 0x01234ABCDEF...
        -- Without a valid signature, enclave operations will fail.
    )
);
GO
